server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_project_scheduler
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yonandaputri12@gmail.com
    password: xummumpzrpuolzaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  baseUrl: http://localhost:8088
